openapi: 3.0.0
info:
  title: PlayZone API
  version: 0.1.0
paths:
  /health:
    get:
      responses:
        '200':
          description: ok
  /auth/profile:
    get:
      responses:
        '200':
          description: user profile
  /streams:
    get:
      summary: List live streams
      parameters:
        - in: query
          name: q
          schema: { type: string }
      responses:
        '200':
          description: list
  /chat/{roomId}/messages:
    get:
      responses:
        '200':
          description: list messages
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text: { type: string }
      responses:
        '201':
          description: created
